yolo_model:

  config_file:
    name: yolov3_fs.cfg
  weight_file:
    name: yolov3_fs.weights
  threshold:
    value: 0.6
  detection_classes:
    names:
      - blue_cone
      - yellow_cone
      - orange_cone
      - large_cone
